---
# yamllint disable rule:truthy
# yamllint disable rule:line-length

name: Molecule

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - debian11
          - debian10
          - ubuntu2004
          - ubuntu1804
          - centos8
          - centos7
          - rockylinux8
          # - almalinux8  #TODO

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip3 install molecule[docker] ansible

      - name: Run Molecule tests
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

...
